version: "2"

services:

  proxy:
    build: ./nginx
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - backend

  api:
    image: parunruaivo/api-presentation
    container_name: api
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
    - db-volume:/data/db
    networks:
      - backend

volumes:
  db-volume:
    driver: local
networks:
  backend:
    external: true


