version: '2'

services:
  proxy:
    image: nginx
    ports:
      - '80:80'
    depends_on:
      - api
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - backend

  api:
    image: parunruaivo/api-presentation
    restart: always
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
   image: mongo
   restart: always
   volumes:
    - db-volume:/data/db
    networks:
      - backend

volumes:
  db-volume:

networks:
  backend:
    external: true


